### ISSUE TITLE
ドキュメントのアップデートする

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#129]
試行錯誤の末、ほぼ安定化してきたので、ドキュメントをコードに合わせる。
あと、物理式は、平鍋さんのREADMEへリンクする。

https://github.com/toppers/hakoniwa-px4sim/tree/main/docs/phys_specs

**Comment by tmori** [comment]
# Drone Dynamics の修正

あっさりとこうしました。

https://github.com/toppers/hakoniwa-px4sim/blob/main/docs/phys_specs/component/physics/README.md

**Comment by tmori** [comment]
# RotorとThrustの修正

トップのアーキテクチャの構成要素の表から以下へリンクさせました。既存の自分のドキュメントは削除しました。

https://github.com/toppers/hakoniwa-px4sim/blob/main/docs/phys_specs/component/physics/README.md

**Comment by kenjihiranabe** [comment]
closeします。
