### ISSUE TITLE
環境要因として突風を与えられるようにする

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#140]
Unity内にオブジェクト（風の強さのパラメータを与えておく）置いておいて、そこに入ったら風の強さの入力データを物理側にフィードバックすればやれそうな気がします。衝突と同じやり方。

あとは、風の強さが突然発生するとか時間的に変化させるスクリプトを組んでおけばいろんな状況を試せそうな気がします。

**Comment by kenjihiranabe** [comment]
簡単に考察すると、空間的に一様な風は、トルクにならないため、並進方向のみに力がかかります。もし力でやろうとすると、acceleration in body に外力の仮引数が追加されそうです。
ただし、飛行機には対空速度と大地速度があり、現在は一致してます(向かい風でも風なしで普通に進む)。とりあえずこのままいくかな。

**Comment by tmori** [comment]
こちらで対応されていますので、クローズしますね。

https://github.com/toppers/hakoniwa-px4sim/issues/230
