### ISSUE TITLE
プラント物理モデルを、制御のために線形化して行列で表現してみたい。

### ISSUE THREAD

**Issue by kenjihiranabe** [toppers/hakoniwa-px4sim#248]
ちょっと調査。
$\sin, \cos$ はなんとかなるが、この2箇所は無理に思える。。。あとはできそう。

![image](https://github.com/toppers/hakoniwa-px4sim/assets/1093925/6e62e23f-aa5d-409d-a8de-8635af856d5a)

**Comment by kenjihiranabe** [comment]
$u,v,w$ は $0$ に近くないが、 $p,q,r$  を近似的に $0$ にすると上記は消える。強く回転していない、という仮定にすることは妥当なのか、判別がつかない。

**Comment by kenjihiranabe** [comment]
線形化するには、２つの方針がありそう。

1. cos θ =1, sin θ = θ （角度の傾きはほんのちょっと）、また、(p, q, r) = 0（ 回転していない）として x' = Ax + Bu を作る。これは、結果的にコリオリ力、ジャイロ効果を無視することになる。（おそらく金沢の先生はこの方法か？証拠：d(φ, θ, ψ)/dt と(p, q, r）の関係する行列Aの成分が、単位行列になっているので、少なくとも角度についてはその方針。）
3. 水平飛行定常状態(p=p0, q=q0, r=r0, θ=θ0...)からの差分Δp, Δq, Δr, Δθ、で立式する。結果としては、x=x0+Δx として計算出力することになる。
https://www.docswell.com/s/Kouhei_Ito/KDVNVK-2022-06-15-193343#p4

本当は、2でやるのが正確。まずは、1と赤坂先生モデルでやって比較してみるか（これはすぐできる）。

**Comment by kenjihiranabe** [comment]
検討中。1 の場合、ほとんど何も加工しないで、thrust と torque を それぞれ w, (φ,θ, ψ) の時間微分に伝えるだけのシンプルなもでるになった。（しかし赤坂先生の行列とはずれている）
２の場合の導出を手で行なった。両方あっていると思われる。
ここに、計算シートを置いておく。
計算したシート
<img width="1259" alt="image" src="https://github.com/toppers/hakoniwa-px4sim/assets/1093925/682c987f-3ae4-4dbc-bfad-ec0f277ee384">

計算過程
[drone_linearize2.pdf](https://github.com/user-attachments/files/16103787/drone_linearize2.pdf)
[drone_linearize3.pdf](https://github.com/user-attachments/files/16103788/drone_linearize3.pdf)
[drone-linearize1.pdf](https://github.com/user-attachments/files/16103789/drone-linearize1.pdf)

**Comment by kenjihiranabe** [comment]
@tmori さん、第一バージョンとして、ホバー位置で線形化して、dx/dt = Ax +Bu の形で動く物理モデルを作りました。
インターフェイスは matlab i/f を使っています。ソースコードは１本のみ。

matlab で mi_drone_acceleration() 関数を呼び出している位置で、drone_acceleration_by_linear_at_hover() 関数を呼び出してください。並進と回転のごくごく簡単なテストをして、既存の物理モデルと大きな乖離がないかだけ確かめました。

CMakeList.txt も書き換えていますので、注意してください。本体とのリンク方法はよくわからなかったので、加えていません。
以下、コミット分です。
https://github.com/toppers/hakoniwa-px4sim/commit/d6c16d249ca4ea933e18b142eb23022a25119d2d

**Comment by tmori** [comment]
ひとまず、こんな感じでリンクできるようにしました。

DRONE_SIMPLE_PHYSICSの定義を有効化してもらえればリンクされます。（デフォルトは従来のもの）

https://github.com/toppers/hakoniwa-px4sim/commit/b04f4dd2404e845afaec0628f82bdba2e3def147

**Comment by tmori** [comment]
# ログを取りました。

* 従来のもの
  *  [drone_log_real.zip](https://github.com/user-attachments/files/16123878/drone_log_real.zip)
* 線形モデルのもの
  * [drone_log_simple.zip](https://github.com/user-attachments/files/16123883/drone_log_simple.zip)

**Comment by tmori** [comment]
#  Z軸

## 従来

<img width="891" alt="スクリーンショット 2024-07-08 16 07 13" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/d325270e-20f5-4be8-84b5-1392f65d1bfa">

## 線形モデル

<img width="896" alt="スクリーンショット 2024-07-08 16 07 39" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/ae4f69e5-2f6c-4930-a2ae-4134f4a2809c">

**Comment by tmori** [comment]
# ロール

## 従来
<img width="912" alt="スクリーンショット 2024-07-08 16 09 23" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/d7e80921-e58a-403b-82ae-35e14ab42880">


## 線形モデル

<img width="902" alt="スクリーンショット 2024-07-08 16 09 46" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/579d02e6-7288-4769-9a79-2af3af57ac32">

**Comment by tmori** [comment]
# ピッチ

## 従来

<img width="914" alt="スクリーンショット 2024-07-08 16 10 38" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/77dbb67c-9b6c-4d03-a76c-58aed218b02e">

## 線形モデル

<img width="906" alt="スクリーンショット 2024-07-08 16 11 02" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/e9bedaa4-fa49-46f9-8836-7cd22f84639d">

**Comment by tmori** [comment]
# ヨー

## 従来
<img width="883" alt="スクリーンショット 2024-07-08 16 13 09" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/ae776250-7e25-4cb3-8df8-e4429db7d31b">

## 線形モデル
<img width="883" alt="スクリーンショット 2024-07-08 16 13 31" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/20346a9a-d140-4bd1-964f-f0f9d17dbfae">

**Comment by kenjihiranabe** [comment]
ありがとう！おどろくほど似てますね。びっくり。結局フィードバック制御さえしていれば、おおまかな線形化と変わらないんですね。

**Comment by kenjihiranabe** [comment]
プラント側の線形化なので、実験した、としてクローズ。
