### ISSUE TITLE
地面の上でドローンが物理的に停止できるようにできないか

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#252]
# 背景

東尋坊観光を考えた場合、海面を０mとしたいので、ドローンの初期位置は60m近くになる。

現状の実装では、60m地点を初期位置としても重力の影響で落ちてしまう。
これを回避するために、初期位置の下にUnityコライダーをつけて干渉させてみたが、機体が反発してどこかに飛んでいってしまう。

**Comment by kenjihiranabe** [comment]
本当は着陸時は地面からの空気反力などの影響があるのと、うまく速度０で着地したいので、別モード（状態遷移）でやる必要があるらしい。地面は壁と違う地面フラグをつけておいて、衝突したら、速度を0にしてしまうのはどう？

**Comment by tmori** [comment]
理解しました！

**Comment by kenjihiranabe** [comment]
弾性係数0の壁でもよいが、、、たぶん後で着陸に関する手はどこかで入ると思う。

**Comment by tmori** [comment]
衝突検出時の現行のデータ構造：

https://github.com/toppers/hakoniwa-ros2pdu/blob/cb18654fcc89afc9341c7cded2c781fc524f5b93/workspace/src/hako_msgs/msg/Collision.msg#L1-L5

**Comment by tmori** [comment]
restitution_coefficient　は、Unity側で、1.0固定で設定しているけど、地面検出時は、0.0にして判定させるのが手っ取り早い。
