### ISSUE TITLE
Python APIの制御プログラムのパラメータを外部ファイル化する

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#263]

**Comment by tmori** [comment]
ひとまず、ローダーを追加した。

https://github.com/toppers/hakoniwa-px4sim/commit/1c646e16a96fefe411803b6fbb8bdf708c4566ce

**Comment by tmori** [comment]
問題は、既存コードをどう直すか。

**Comment by kenjihiranabe** [comment]
そうねー、うまく局所化しておいた方がよさそうな。。

**Comment by tmori** [comment]
既存コードを大改修。

https://github.com/toppers/hakoniwa-px4sim/commit/17981a8df32a1aedaf5a7caafdeb7a577383f77e

残作業：
* RadioControlのマクロ決め打ち部分の修正
* PS4コントローラとPython APIでのパラメータ変更方法の検討
* リグレッション確認テスト
