### ISSUE TITLE
制御理論ベースでPIDパラメータを検討できる環境を作りたい

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#272]
# 制御評価方法

まずは、定量評価して最適なパラメータを選定するためのやり方を考える

- [x] #273
- [x] #274
- [x] #275
- [x] #276

**Comment by tmori** [comment]
全ての修正完了したのでクローズします。

**Comment by kenjihiranabe** [comment]
おめでとう 👏
