### ISSUE TITLE
analyze ツールに閉ループ極の表示

### ISSUE THREAD

**Issue by kenjihiranabe** [toppers/hakoniwa-px4sim#346]
analyze ツール --response poles では現在、開ループ(L(s))の零と極を表示するが、安定性別のために、
W(s)= L/(1+L)の極、すなわち、L(s)+1 = 0 の根を表示できるとよい。

足立先生教科書 5.3
<img width="376" alt="image" src="https://github.com/user-attachments/assets/697c277a-5d90-41b7-b2be-d0c818ab9816">
足立先生教科書 6.1.2 
<img width="494" alt="image" src="https://github.com/user-attachments/assets/e7ebaba0-f565-4bee-9504-b97ce76baf76">

**Comment by tmori** [comment]
これやりたい。

**Comment by tmori** [comment]
こちらで管理します。

https://github.com/toppers/hakoniwa-drone-education/issues/25
