### ISSUE TITLE
プラントのシステム同定可能なモジュールを作る

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#351]
# 追加対象

- ルンゲクッタモデルの境界条件を取り払ったものの追加

**Comment by tmori** [comment]
# 実験結果

## 測定条件

- 入力
  - sineカーブ
  - 周波数：1Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：100秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 100 1 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

## 実験結果

![image](https://github.com/user-attachments/assets/65df741b-b5e6-4f26-964d-49b757d31d8f)

**Comment by tmori** [comment]
# 実験結果(0.1Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：0.1Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：1000秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 1000 0.1 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 955 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 500 --duration 40
```

![image](https://github.com/user-attachments/assets/15d5cfd4-54d3-4888-94ce-f4d094265237)

ローター回転数：
![image](https://github.com/user-attachments/assets/cdb6d275-09cb-4d67-9512-625eb09cf4dd)

**Comment by tmori** [comment]
# 実験結果(0.01Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：0.01Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：1000秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 1000 0.01 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 955 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 500 --duration 400
```

![image](https://github.com/user-attachments/assets/1520a273-1030-42f7-86ed-e0d97323e582)

ローター回転数：
![image](https://github.com/user-attachments/assets/c424e168-7f93-4219-afb8-24b3b0938e22)

**Comment by tmori** [comment]
# 実験結果(10Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：10Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：100秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 100 10 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 95 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 80 --duration 0.4
```

![image](https://github.com/user-attachments/assets/fb6ce632-8f13-47cf-ae94-42d2973bc580)

ローター回転数：
![image](https://github.com/user-attachments/assets/83b9daa6-3a18-4173-aba5-82eb2a5d0f3f)

**Comment by tmori** [comment]
# 実験結果(100Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：100Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：10秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 10 10 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 5 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 3 --duration 0.5
```

![image](https://github.com/user-attachments/assets/8517156a-e361-4e2e-a68e-5ec0f5009aa7)

ローター回転数：
![image](https://github.com/user-attachments/assets/e1b18b07-0098-4160-aa5c-a76b9df3dedf)

**Comment by kenjihiranabe** [comment]
メモ：座標の正負の関係で、出力はもともと 180° ずれていることに注意。

**Comment by tmori** [comment]
# 実験結果(3Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：3Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：300秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 300 3 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt 
```

```
bash ../src/tools/show-inout.bash 50 250 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --duration 1
```

![image](https://github.com/user-attachments/assets/9ed2fcea-c9d6-4018-a27c-ca0895dbbb78)

ローター回転数：
![image](https://github.com/user-attachments/assets/71db8604-9278-4dfe-b8d6-730bef21684f)

**Comment by tmori** [comment]
# 実験結果(30Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：30Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：300秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 300 30 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt 
```

```
 bash ../src/tools/show-inout.bash 100 200 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --duration 0.1
```

![image](https://github.com/user-attachments/assets/3c0458cd-55d0-44f7-bddf-04b7fee1473e)

ローター回転数：

![image](https://github.com/user-attachments/assets/ac312e2a-0248-454b-a352-cd1e816b1e2c)

**Comment by tmori** [comment]
# 実験結果(0.3Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：0.3Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：1000秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 1000 0.3 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 955 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 500 --duration 10
```

![image](https://github.com/user-attachments/assets/e70dc402-9cf4-4db4-8dac-c26925e85ed2)

ローター回転数：
![image](https://github.com/user-attachments/assets/0d2f1ec8-e3f7-4b01-931a-442451df867f)

**Comment by tmori** [comment]
# 実験結果(0.03Hz)

## 測定条件

- 入力
  - sineカーブ
  - 周波数：0.03Hz
  - Thrust：6.585

- 出力
  - 高度の速度：Vz
 
- データの範囲
  - 計測時間：1000秒

## 実行コマンド

```
bash -x ../src/tools/eval-plant.bash 1000 0.03 T:6.585 Tx:0 Ty:0 Tz:0 | tee log.txt
```

```
bash ../src/tools/show-inout.bash 5 955 in.csv drone_log0/drone_dynamics.csv Vz
```

## 実験結果

```
 python ../src/tools/hako_TimelineAnalyzer.py  input.csv output.csv  --diff --columns input.value output.Vz  --diff --start_time 500 --duration 100
```

![image](https://github.com/user-attachments/assets/780b1db5-b4ef-42ee-be89-6c966be29521)

ローター回転数：
![image](https://github.com/user-attachments/assets/006c1bee-d9e3-4650-8825-ca8984edb945)

**Comment by kenjihiranabe** [comment]
とりあえず、グラフにしてみました。後で考察書きます。
https://docs.google.com/spreadsheets/d/1JACdNpwAYr-OUya5DmPa8r_1QfsI-4M4G-kJ_zLCvQ0/edit?usp=sharing

![image](https://github.com/user-attachments/assets/569c7105-7243-40fe-a376-5a9e7976fa68)
