### ISSUE TITLE
[マニュアル] Pythonアプリの実行で落ちる

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#352]
# 発生環境
Windows11＋WSL環境

# オペレーション

マニュアル（windows_hakowin_installer.pdf）の4節において、「4.2.3. Python API サンプルアプリの起動」が上手く実行できなかった

# 原因
Pythonに必要なライブラリがインストールされていなかった
 - numpy
 - pygame

**Comment by buildko89** [comment]
ここに追記済み！
https://github.com/toppers/hakoniwa-px4sim/blob/develop/docs/manual/windows_hakowin_installer.md

**Comment by tmori** [comment]
[PR](https://github.com/toppers/hakoniwa-px4sim/pull/355)ありがとうございます！
