### ISSUE TITLE
version 2.7.0 のリリース

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#358]
# 機能拡張内容

- [x] #363
- [x] #367
- [x] #374
- [x] #366
- [x] #364
- [x] #368
- [x] #369
- [x] #370
- [x] #371
- [x] #359
- [x] #360
- [x] #382
- [x] https://github.com/toppers/hakoniwa-px4sim/issues/387
- [x] #372
- [x] #373

**Comment by buildko89** [comment]
@yamati-kz さん
[windows_hakowin_installer.md](https://github.com/toppers/hakoniwa-px4sim/blob/main/docs/manual/windows_hakowin_installer.md)の追記の件は、了解です。

ちょっと別件で必要になり、突貫で作ってしまったところがあります。

ご提案の章立てのイメージは良いかと思います。
ゲームパッドのデバッグについては、追記した方が、無難かと思います。

今後、なるべくドキュメントを一本化していく方向で整理予定ではあります。

**Comment by yamati-kz** [comment]
@buildko89 さん　ご返事ありがとうございます。
https://github.com/toppers/hakoniwa-px4sim/pull/361 にて追記してみました。
記載して記述があるといいかなと思った内容です。

> ゲームパッドのデバッグについては、追記した方が、無難かと思います。

私自身Windowsで試したことがないので、今後、手順書を試しながらご提案させていただければと思います。

**Comment by buildko89** [comment]
issue ♯362は対応します。少々お待ちください。

**Comment by tmori** [comment]
自分は、以下のissueをやっていきますね。

 https://github.com/toppers/hakoniwa-px4sim/issues/368
 https://github.com/toppers/hakoniwa-px4sim/issues/369
 https://github.com/toppers/hakoniwa-px4sim/issues/370
 https://github.com/toppers/hakoniwa-px4sim/issues/371
 https://github.com/toppers/hakoniwa-px4sim/issues/359
 https://github.com/toppers/hakoniwa-px4sim/issues/360

**Comment by buildko89** [comment]
@yamati-kz さん @tmori さん
issue #362対応しました。PR投げました。

**Comment by yamati-kz** [comment]
@buildko89 さん @tmori さん
https://github.com/toppers/hakoniwa-px4sim/issues/362 ご対応ありがとうございました。
