### ISSUE TITLE
リリース用のバイナリ作成（Windows）

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#374]

**Comment by buildko89** [comment]
対応しておきます！

**Comment by tmori** [comment]
ありがとうございます！

**Comment by buildko89** [comment]
@tmori さん
v2.7.0のWindowsの動作確認ですが、sampleのPythonアプリまでは確認できました。
→ 大分変ったので、環境設定の理解に時間掛かった…
→ ただ、rc.pyなどプロポ操作ができないようですので、デバッグ中です～

**Comment by buildko89** [comment]
@tmori さん
これは、インストーラに含めますので。

**Comment by tmori** [comment]
配置されていることを確認しましたのでクローズしますね。

https://github.com/toppers/hakoniwa-unity-drone-model/releases/tag/v2.2.0
