### ISSUE TITLE
ドキュメントにリンク切れ発見

### ISSUE THREAD

**Issue by kenjihiranabe** [toppers/hakoniwa-px4sim#387]
下記、dronoe_config.json がリンク切れ

https://github.com/toppers/hakoniwa-px4sim/blob/main/hakoniwa/README-ja.md#%E6%A9%9F%E4%BD%93%E3%81%AE%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E8%AA%AC%E6%98%8E

![image](https://github.com/user-attachments/assets/0caf6e57-03f0-424d-b394-4b42cea6d358)

**Comment by tmori** [comment]
修正しました。
