### ISSUE TITLE
Omega の単位（rpm -> rad)

### ISSUE THREAD

**Issue by kenjihiranabe** [toppers/hakoniwa-px4sim#390]
$\omega_0$ - 釣り合いでの回転数

の単位ですが、physics 側は、rad/s ですべて対応します。関数仕様や 

- `rotor_omega_acceleration()` が返す値
- `body_torque()`,` rotor_anti_torque()`,  に入力する値

の計算はすべて同じです（コメントのみの修正）。

こうへいさんの資料でも 
- $\omega_0 = \sqrt{mg/4Ct}$

となっていて、これを現在の config で計算すると、 
- $\omega_0 = 1448 \quad rad/s$
 
になります。RPM 単位にすると、 （この issue の後で間違いがあり、訂正）
~~HoveringRpm = omega_0 / 2 π rpm~~
~~HoveringRpm = 230.46  rpm~~

- $HoveringRpm = 60 \omega_0/2 \pi \quad rpm$
- $HoveringRpm = 13827 \quad rpm$
 
となります。

@tmori  そちらで修正しやすいように直してください。そちらから見ても、「いれぽんだしぽん」なので、シミュレーションに影響しないと思っていますが。。。。

**Comment by tmori** [comment]
今日、電車でやります。

**Comment by tmori** [comment]
# 修正案

1. 機体のコンフィグ仕様は変更なし
2. 機体パラメータをランタイム側でrad/sに変換する

変換が必要なパラメータ：
* rotor.Kr
* rotor.rpmMax
* thruster.HoveringRpm

**Comment by tmori** [comment]
# HoveringRPMの変更ポイント

https://github.com/toppers/hakoniwa-px4sim/blob/b6a0bae8c15d5031c156bb529e7f4b9d896053e0/hakoniwa/src/assets/drone/aircraft/aircraft_factory.cpp#L144-L177

**Comment by tmori** [comment]
# rotor.Kr

マクロ値を書き換える。

https://github.com/toppers/hakoniwa-px4sim/blob/b6a0bae8c15d5031c156bb529e7f4b9d896053e0/hakoniwa/src/assets/drone/aircraft/aircraft_factory.cpp#L53

**Comment by tmori** [comment]
# rpmMaxの変更ポイント


マクロ値とマクロ名を書き換える。



https://github.com/toppers/hakoniwa-px4sim/blob/b6a0bae8c15d5031c156bb529e7f4b9d896053e0/hakoniwa/src/assets/drone/aircraft/aircraft_factory.cpp#L51C9-L51C16

**Comment by kenjihiranabe** [comment]
ここ、注意です。rpm でセッティングならば、2 $pi$ で割ってください。
https://github.com/search?q=repo%3Atoppers%2Fhakoniwa-px4sim%201448&type=code

**Comment by tmori** [comment]
> ここ、注意です。rpm でセッティングならば、2 π で割ってください。 https://github.com/search?q=repo%3Atoppers%2Fhakoniwa-px4sim%201448&type=code

了解です！
KrとRpmMaxも同じですよね。

**Comment by tmori** [comment]
@kenjihiranabe 


![Image](https://github.com/user-attachments/assets/bde94663-4408-40ee-aff5-fbc28bb2a9d1)

ここの変換ですが、
RPMは回転数/分なので、
rad/secからRPMに変換するには

```
ω0 x 60/2π
```

ではないでしょうか？

**Comment by tmori** [comment]
一旦、コード側の修正終わりました。パラメータの方は、平鍋さんの回答あった後に対応予定です。

https://github.com/toppers/hakoniwa-px4sim/commit/297bc6a8a31eae7a6c1c2066f28f01a8a5a0e302

**Comment by kenjihiranabe** [comment]
>ω0 x 60/2π
>ではないでしょうか？

ですです！

**Comment by tmori** [comment]
@kenjihiranabe 修正しました。

ご確認ください。

https://github.com/toppers/hakoniwa-px4sim/commit/2b985cde0590e7bc7d559be7802fd14348d10d07

**Comment by tmori** [comment]
@kenjihiranabe 
対応完了しましたので、ご確認ください！

https://github.com/toppers/hakoniwa-px4sim/pull/408

**Comment by kenjihiranabe** [comment]
動作確認できたので、クローズします。
