### ISSUE TITLE
ラジコン操作で、ドローンを起動ポイントに戻す機能が欲しい

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#402]
# 背景

ドローンがどっかに飛んでいってしまった時に、もう元に戻らなくなってしまうことが多々ある。

# 仕様案

以下の２つで対応できないか。

- ラジコン操作キーを追加して、そのボタンが押されたら強制で戻ってくる
- ホームに戻るpythonアプリを起動したら、戻ってくる（ラジコン操作は受け付けなくする）

**Comment by tmori** [comment]
PR 出しましたー。

https://github.com/toppers/hakoniwa-px4sim/pull/404

**Comment by buildko89** [comment]
@tmori さん
確認しました。マージしやす。

**Comment by buildko89** [comment]
動かすの楽しみ～
