### ISSUE TITLE
機体パラメータの変更要望

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#414]
* パラメータAをCtにしたい。
* ホバリング時と最大RPMを逆算で求めたい。

**Comment by tmori** [comment]
# 修正対象パラメータ

- thruster
  - HoveringRpm：削除
  - parameterB：名前変更 Cq
  - parameterJr：名前変更 Jr
- rotor
  - Kr：削除
  - rpmMax：削除
  - Ct：追加

**Comment by tmori** [comment]
RPMの計算式：

```
HoveringRPM = sqrt(4 * Ct * m * g/N)
```

**Comment by kenjihiranabe** [comment]
HoveringRPM = sqrt(m * g/ Ct * N)

ラジアン注意にて。

**Comment by tmori** [comment]
```
Tr=J*Rm/(Dm*Rm+K*K+2*Rm*Cq*ω_0)
```

**Comment by tmori** [comment]
この対応をすると、バッテリーとミキサーは必ずつけないといけなくなることに気づきました。
まー、いっか。。

**Comment by tmori** [comment]
複数のコンフィグパターンのサポートは正直辛くなってきたので、version2.8.0では、この構成オンリーでいきます。

**Comment by tmori** [comment]
修正完了ー

**Comment by kenjihiranabe** [comment]
動いたので、クローズ。
