### ISSUE TITLE
クオータニオン対応

### ISSUE THREAD

**Issue by kenjihiranabe** [toppers/hakoniwa-px4sim#433]
いつかやる
https://interface.cqpub.co.jp/wp-content/uploads/IF03_074-080_E04-1.pdf

![Image](https://github.com/user-attachments/assets/21311448-8482-4372-8116-a1ea9254f94c)

検討事項
- physics に入れる部分と body_frame に入れる部分の分割（Quaternion状態を保持する必要がある）
- physics の触る関数と関数名（オーバーロードで行けるか）
- glm を使うかどうか

**Comment by kenjihiranabe** [comment]
Quaternion 、Euler 角相互変換についてより詳しい記事（上記記事と同一著者）
https://interface.cqpub.co.jp/wp-content/uploads/IF03_054-069_A104-3.pdf

![Image](https://github.com/user-attachments/assets/1a676d78-348f-4225-8aef-888a560a008f)
![Image](https://github.com/user-attachments/assets/92e24dff-f707-4e1b-8ca3-1f8fd3239fba)
![Image](https://github.com/user-attachments/assets/baa1705d-cbc6-4e8e-bd50-c21a5c16a162)

**Comment by kenjihiranabe** [comment]
オイラー角とクオータニオン対応メモ。

## 分かったこと

- クオータニオンは「姿勢」を表し、同じ役割のオイラー角と１：１対応する（時間微分でなくこの両者が相互変換）。
- 現在の姿勢は、クオータニオンを正として維持、そこから、必要時に上記によってオイラー角に変換するべき。
- よって、aircraft 内に姿勢クオータニオンを保持する必要がある。そして、クオータニオンの時間微分を積分してアップデートしていく。
- クオータニオンの時間微分は、 $\dot{q} = \frac{1}{2} q \otimes w$ である。（野波先生の本には1/2がヌケ）

## 対応方針

###  drone_physics

現在の関数 euler_rate_from_body_angular_velocity（ピッチ90°付近で内部0割破綻する） に対応する新たな関数、quaternion_velocity_from_body_angulear_velocity を作成する。これは上記時間微分を担当。結果 $\dot{q}=\frac{dq}{dt}$ を返す。
- 
- 
### - aircraft

DroneDynamicsBodyFrame クラス（３つある）のなかに、EulerType(initial, angle), EulerRateType(angularVelocity), それぞれ対応するクオータニオンを保持する。
  - drone_dynamics_body_frame.hpp
  - drone_dynamics_body_frame_rk4.hpp
  - drone_dynamics_body_frame_matlab.hpp

上記 physics 側関数を呼び出して、eular でなく、quaternion を計算、積算する。

## 注意

- クオータニオン要素の並び順には二つの流儀があり、ベクトルとしての順番に注意。 (q0,q1,q2,q3) として、 xyzw か wxyz か。
- 特に glm を使う場合、順序は xyzw となっている（0.997以降。0.997以前は wxyz らしい）https://qiita.com/syoyo/items/0177fee6778746207ed7
- 最新版は、1.0系になっているので、hakoniwaもアップグレードした方がよい。（本家 https://github.com/g-truc/glm ）
- Quaternionとオイラー角の変換詳説。このページの書き方だと、先頭の回転順xyz （z-y-xの順）に対応する。
https://qiita.com/aa_debdeb/items/3d02e28fb9ebfa357eaf

**Comment by kenjihiranabe** [comment]
まずは、オイラーとクオータニオンの相互変換

- euler_from_quaternion
- quaternion_from_euler

作成。テストを回すが、特殊ケースで $\theta = \pm 90$ のときに特殊扱い必要。テストが失敗する例は、 $q=[-1/2, -1/2, -1/2, 1/2]^T$ で、これを図示してみた。$cos \theta = 0$ すなわち、ピッチ角が垂直のときにジンバルロックが起こるので、Q->E の解は一意に決まらなくなる。その特殊ケースを入れて、再度テスト。ピッチが、90°の近傍 0.001 範囲にあるときは、特殊なロジック（ $\phi=0$ ）を入れて走らせたら、全テストケースが通るようになった。なので、とりあえず、これで変換部分は終わって、本丸の Quaternion の時間微分に入る。
もしかしたら、ground_vector_from_body_frame など、EulerAngleType を姿勢としてパラメータに渡しているところは、Quaternion 姿勢に変えるかも。（Quaternion -> Euler でも姿勢は 0割などなく、安定）。

![Image](https://github.com/user-attachments/assets/b4bbac1c-8f7e-41df-985f-5805c05949e6)

**Comment by kenjihiranabe** [comment]
本丸の Quaternion の時間微分できました。これで、euler_rate_from_body_angular_velocity がクオータニオン化できます。
physics 側一旦終了です。aircraft 側での変更方針について、明日、説明しますね。
https://github.com/toppers/hakoniwa-px4sim/commit/1a6564fda027912bc3e648654da9d11e697bf422

**Comment by kenjihiranabe** [comment]
クオータニオンバージョンで飛んだので、残りは、

- [ ] drone_dynamics_body_frame.hpp の整理

です。本日の議論です。

![Image](https://github.com/user-attachments/assets/e2bf86d5-db7f-4a53-aebb-3353abe0112c)

**Comment by tmori** [comment]
あー、あと、センサ系に影響ないかはPX4で実験してみる必要があると思われます。

空いた時間でトライしてみます。

**Comment by kenjihiranabe** [comment]
動いたので、クローズ。
