### ISSUE TITLE
トルク側にも空気摩擦を数式に組み込んではどうか

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#56]

**Comment by kenjihiranabe** [comment]
ドローンの場合、速度がどんどん上がることはあり得るので、キャップをかけるいみでも、空気摩擦は有効に機能します。
でも、各速度については、「各速度がどんどん上がる」ことは実質的なユースケースからあまり考えられないと思います。なので、微調整レベルではアリと思うのですが、これが実質上の効果をあげるとは考えにくいです。

**Comment by tmori** [comment]
なしでも良さそうなのでクローズします。
