### ISSUE TITLE
右方向へ移動して目標値で停止するテストを実施する

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#83]
# テスト環境

* Mac 環境
* 機体の移動にはQGCを利用

# テスト目的

右へ移動して目標値で停止する機体パラメータを探索する

現時点で安定してホバリング＆前進して停止するパラメータは以下：

```
{
    "simulation": {
      "lockstep": true,
      "timeStep": 0.003,
      "logOutputDirectory": "./",
      "logOutput": {
        "sensors": {
            "acc": true,
            "gyro": true,
            "mag": true,
            "baro": true,
            "gps": true    
        },
        "mavlink": {
            "hil_sensor": true,
            "hil_gps": true,
            "hil_actuator_controls": true
        }
      },
      "mavlink_tx_period_msec": {
        "hil_sensor": 3,
        "hil_gps": 3
      },
      "location": {
        "latitude": 47.641468,
        "longitude": -122.140165,
        "altitude": 121.321,
        "magneticField": {
          "intensity_nT": 53045.1,
          "declination_deg": 15.306,
          "inclination_deg": 68.984
        }  
      }
    },
    "components": {
        "droneDynamics": {
            "physicsEquation": "BodyFrame",
            "airFrictionCoefficient": 0.2,
            "inertia": [ 0.05, 0.05, 0.05 ]
          },
          "rotor": {
            "tau": 0.001,
            "k": 1000.0,
            "rpmMax": 2200
          },
          "thruster": {
            "rotorPositions": [
              {"position": [  0.3,  0.3, 0 ], "rotationDirection":  1.0 },
              {"position": [ -0.3, -0.3, 0 ], "rotationDirection":  1.0 },
              {"position": [  0.3, -0.3, 0 ], "rotationDirection": -1.0 },
              {"position": [ -0.3,  0.3, 0 ], "rotationDirection": -1.0 }
              ],
            "parameterA": 2.18e-06,
            "parameterB": 6.94444e-12,
            "parameterJr": 0.0
          },
          "sensors": {
            "acc": {
              "sampleCount": 4,
              "noise": 0
            },
            "gyro": {
              "sampleCount": 4,
              "noise": 0
            },
            "mag": {
              "sampleCount": 4,
              "noise": 0.0001
            },
            "baro": {
              "sampleCount": 4,
              "noise": 0
            },
            "gps": {
              "sampleCount": 4,
              "noise": 0
            }
          }
    }
  }
  
```

# テスト内容

機体をホバリングした状態になったら、QGCで機体の右方向を目標値として設定して移動させる

期待値：目標値で機体が停止する

テストエビデンス：
機体のロギングデータ（安定度を見たいため）

**Comment by tmori** [comment]
# テスト結果（NG）

右へ水平移動することを確認したが、目標値へ到達して、しばらくすると、PX4が以下の警告を出力し、
機体が不安定になった。

```
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Compass needs calibration - Land now!	
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
```

**Comment by kenjihiranabe** [comment]
いくつか僕の解釈を書いておくので、認識があっているか確認お願い。
![image](https://github.com/toppers/hakoniwa-px4sim/assets/1093925/0c799148-5d4c-4854-89fe-338f0e3a2b14)
仮説：駆動側からみて、すごく「軽い」ものを制御しているのではないか？慣性側（m, I) の値と駆動側(Thrust, Torque)のバランスが間違っていないか？
質問：ASIMのログでもこのくらい細かい振動していますか？

**Comment by tmori** [comment]
> いくつか僕の解釈を書いておくので、認識があっているか確認お願い。 

すごく細かく制御されているのは同じ人市k知恵す。
あと、初動の動きも、その通りだと思います・

> 質問：ASIMのログでもこのくらい細かい振動していますか？

AirSimの方は、内部データが取れないので、ちょっとわからないですが、
QGCで姿勢角の動きを見ていた感じからすると、すごく安定していたと思います。

> 仮説：駆動側からみて、すごく「軽い」ものを制御しているのではないか？慣性側（m, I) の値と駆動側(Thrust, Torque)のバランスが間違っていないか？ 

なるほど。

> "inertia": [ 0.05, 0.05, 0.05 ]

イナーシャが小さすぎるかもしれないですね。

**Comment by tmori** [comment]
AirSimの右方向移動のログ：

[log.zip](https://github.com/toppers/hakoniwa-px4sim/files/13712866/log.zip)

**Comment by tmori** [comment]
AirSim:
![image](https://github.com/toppers/hakoniwa-px4sim/assets/164193/ff6953cc-e619-4069-be9a-0e7efd192533)

QGC:
![image](https://github.com/toppers/hakoniwa-px4sim/assets/164193/d1bfc5f8-86cc-46d1-9122-7cab1bfcd22c)

**Comment by tmori** [comment]
# テスト内容と結果２（NG）

## テスト内容

機体をホバリングした状態になったら、QGCで機体の右方向を目標値として設定して移動させる

期待値：目標値で機体が停止する

## コンフィグパラメータ

```
{
    "simulation": {
      "lockstep": true,
      "timeStep": 0.003,
      "logOutputDirectory": "./",
      "logOutput": {
        "sensors": {
            "acc": true,
            "gyro": true,
            "mag": true,
            "baro": true,
            "gps": true    
        },
        "mavlink": {
            "hil_sensor": true,
            "hil_gps": true,
            "hil_actuator_controls": true
        }
      },
      "mavlink_tx_period_msec": {
        "hil_sensor": 3,
        "hil_gps": 3
      },
      "location": {
        "latitude": 47.641468,
        "longitude": -122.140165,
        "altitude": 121.321,
        "magneticField": {
          "intensity_nT": 53045.1,
          "declination_deg": 15.306,
          "inclination_deg": 68.984
        }  
      }
    },
    "components": {
        "droneDynamics": {
            "physicsEquation": "BodyFrame",
            "airFrictionCoefficient": 0.324,
            "inertia": [ 0.03, 0.03, 0.06 ]
          },
          "rotor": {
            "Tr": 0.1,
            "Kr": 8000,
            "rpmMax": 8000
          },
          "thruster": {
            "rotorPositions": [
              {"position": [  0.3,  0.3, 0 ], "rotationDirection":  1.0 },
              {"position": [ -0.3, -0.3, 0 ], "rotationDirection":  1.0 },
              {"position": [  0.3, -0.3, 0 ], "rotationDirection": -1.0 },
              {"position": [ -0.3,  0.3, 0 ], "rotationDirection": -1.0 }
              ],
            "HoveringRpm": 4000,
            "parameterB":  0.5e-07,
            "parameterJr": 1.0e-08
          },
          "sensors": {
            "acc": {
              "sampleCount": 1,
              "noise": 0
            },
            "gyro": {
              "sampleCount": 1,
              "noise": 0
            },
            "mag": {
              "sampleCount": 1,
              "noise": 0.0001
            },
            "baro": {
              "sampleCount": 1,
              "noise": 0
            },
            "gps": {
              "sampleCount": 1,
              "noise": 0
            }
          }
    }
  }

```

## テスト結果

機体は右方向へ移動したが、しばらくすると落ちてしまう。

また、PX4からは相変わらず、以下の警告メッセージが出力される

```
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
```

**Comment by kenjihiranabe** [comment]
分析しました。Bを1/3 程度にすることで、初動の揺れと最後の揺れも解決できるかも。
![箱庭-12](https://github.com/toppers/hakoniwa-px4sim/assets/1093925/139accb2-bfcb-4736-84f2-9c8daca7872e)

**Comment by tmori** [comment]
落ちる原因はよくわからないのですが、以下のパラメータを調整したところ、落ちなくなりました。

修正前：
　"airFrictionCoefficient": 0.324
　"inertia": [ 0.03, 0.03, 0.06 ]
    "parameterB":  0.5e-07,
修正後：
　"airFrictionCoefficient": 0.1
　"inertia": [ 0.01, 0.01, 0.02 ]
    "parameterB":  2.0e-08,


修正後の結果：

警告はまだ出ます。

```
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
```

ログ一式：

[test_log3.zip](https://github.com/toppers/hakoniwa-px4sim/files/13736244/test_log3.zip)


グラフ（代表的なもの）

<img width="881" alt="スクリーンショット 2023-12-21 14 05 56" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/de7ad72c-9927-4fa3-925c-6022a6ef48fa">

加速度：

![スクリーンショット 2023-12-21 14 06 44](https://github.com/toppers/hakoniwa-px4sim/assets/164193/e3c5fa1d-ce3f-460e-a83c-cd45dd1efd23)


<img width="890" alt="スクリーンショット 2023-12-21 14 07 14" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/eeb42795-1a27-4555-967a-ea95bf01155f">


ジャイロ：

<img width="885" alt="スクリーンショット 2023-12-21 14 07 50" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/3251671f-e5b9-417d-8eab-013ec4222e6b">

Thrust：

<img width="907" alt="スクリーンショット 2023-12-21 14 09 44" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/a0d58322-912f-4fec-af4c-1107bb3578e0">

トルク：

<img width="890" alt="スクリーンショット 2023-12-21 14 09 12" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/c63bda80-798c-4c98-a736-0b9c19c06d5b">

位置：

<img width="897" alt="スクリーンショット 2023-12-21 14 08 31" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/b12cc2e5-c8eb-4f03-9b72-3ca894be04bd">

**Comment by kenjihiranabe** [comment]
32秒から急に右に動き出し
3秒後、35秒で一旦目標値を通り越して
5秒後、40秒でバックして戻っている
40秒から60秒の、20秒間は目標値を行きすぎたり、戻ったりしている。
んですね。つまり、3秒で到達して、20秒、位置合わせしている。

**Comment by tmori** [comment]
#89 の修正を適用した結果

# controls

![スクリーンショット 2023-12-23 9 31 17](https://github.com/toppers/hakoniwa-px4sim/assets/164193/c4dff7fb-5926-4fe1-8dfc-23750c2d041a)


# pos

<img width="885" alt="スクリーンショット 2023-12-23 9 31 55" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/7112ffc4-ee6a-4540-8288-d62c749d1d9b">

# rot

<img width="903" alt="スクリーンショット 2023-12-23 9 32 58" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/995a3339-cdac-455b-9060-2477f81f3e2d">


# acc(x, y)

<img width="923" alt="スクリーンショット 2023-12-23 9 34 06" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/deb02ba7-b800-4da9-a280-f0616459ab15">


# acc(z)

<img width="907" alt="スクリーンショット 2023-12-23 9 35 02" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/cec4a173-a903-4e3a-95b4-7001b9713583">

# gyro

<img width="918" alt="スクリーンショット 2023-12-23 9 35 34" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/bc4210fe-9eb1-4bc1-bc2b-e34835085a02">

# thrust

<img width="889" alt="スクリーンショット 2023-12-23 9 36 08" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/0102f332-a00b-45ec-81a5-d18047d665d0">

# torque

<img width="917" alt="スクリーンショット 2023-12-23 9 36 39" src="https://github.com/toppers/hakoniwa-px4sim/assets/164193/17764e91-e75e-436b-9a48-ce92d133d428">

**Comment by tmori** [comment]
安定して右方向いどうするようになったのでクローズします。
