### ISSUE TITLE
vector_body_to_groundのZ軸の計算に誤りがありました

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-px4sim#89]
該当箇所：

https://github.com/toppers/hakoniwa-px4sim/blob/3572b9bcf2dcee654b73c1b4627e894907827bbf/hakoniwa/src/assets/drone/physics/math_and_physics/math_and_physics.cpp#L75-L76

s_psiとc_psiは、s_phiとc_phiですね。

**Comment by kenjihiranabe** [comment]
fixed https://github.com/toppers/hakoniwa-px4sim/commit/c5a118b656d92641a93a59cd6c4b92f88e7b2782

**Comment by kenjihiranabe** [comment]
自分のところでバグ発見するのショック！！（ユニットテストすり抜けた。。。新しいテスト追加してからクローズします。

**Comment by kenjihiranabe** [comment]
utest.cpp に、このバグ用のテストケースを追加。クローズ。
https://github.com/toppers/hakoniwa-px4sim/commit/1c2fd321b9074cf79ba45838d6d7e0f9501fde8c
